import type { CausalChainLink } from "./ws-types.js";

// ── Structured observation types ─────────────────────────────────────────────

export type MetricObservation = {
  metric: string;
  currentValue: string;
  baselineValue: string;
  timestamp: string;
  severity: "normal" | "warning" | "critical";
};

export type MetricFindings = {
  observations: MetricObservation[];
  anomalyWindow: string;
  summary: string;
};

export type LogObservation = {
  pattern: string;
  count: string;
  firstSeen: string;
  lastSeen: string;
  sample: string;
  sampleLines: string[];
};

export type LogFindings = {
  observations: LogObservation[];
  summary: string;
};

export type InfraObservation = {
  resource: string;
  status: string;
  detail: string;
  timestamp: string;
};

export type InfraFindings = {
  observations: InfraObservation[];
  summary: string;
};

// ── Phase types ──────────────────────────────────────────────────────────────

export type InvestigationPlan = {
  hypotheses: Array<{ hypothesis: string; evidenceNeeded: string }>;
  metricFocus: string[];
  logFocus: string[];
  infraFocus: string[];
};

// ── Report types ─────────────────────────────────────────────────────────────

export type TimelineEvent = {
  time: string;
  event: string;
};

/** A single tool call captured during an evidence phase. Mirrors
 *  `ToolCallRecordSchema` in `src/workflows/schemas.ts`. Used to build
 *  observation-level Grafana deep links in the web UI. */
export type EvidenceToolCall = {
  tool: string;
  args: string;
  resultChars: number;
  /** Short snippet of the actual tool result, shown inline in receipts so the
   *  operator sees the value without clicking through to Grafana. */
  resultExcerpt?: string;
};

/** A candidate root cause the hypothesis loop ranked (Step 2). Mirrors
 *  RankedHypothesisSchema in src/workflows/schemas.ts. */
export type RankedHypothesis = {
  hypothesis: string;
  prediction: Record<string, unknown>;
};

/** A hypothesis the loop tested and ruled out, with the deterministic verdict
 *  ("contradicted" | "absent") that demoted it. */
export type RuledOutHypothesis = {
  hypothesis: string;
  reason: string;
};

/** One hypothesis re-examined by deep mode (Step 3). Mirrors
 *  ReexaminedHypothesis in src/workflows/steps/deep-mode.ts. */
export type DeepModeReexamination = {
  hypothesis: string;
  /** How the loop left it: confirmed (re-tested to refute) or ruled-out (to resurrect). */
  priorStanding: "confirmed" | "ruled-out";
  /** The loop's verdict for it. */
  priorVerdict: "satisfied" | "contradicted" | "absent";
  /** Verdict after deep mode gathered deeper evidence. */
  deepVerdict: "satisfied" | "contradicted" | "absent";
  /** Standing changed: ruled-out→satisfied (resurrected) or confirmed→not-satisfied (shaken). */
  flipped: boolean;
};

/** Deep-mode output (Step 3): the skeptical re-examination of the loop's
 *  conclusion. Unset unless deep mode was triggered. */
export type DeepModeReport = {
  reexamined: DeepModeReexamination[];
  /** Ruled-out hypotheses deeper evidence brought back as live candidates. */
  resurrected: RankedHypothesis[];
  /** Confirmed hypotheses deeper evidence no longer supports. */
  shaken: RankedHypothesis[];
  outcome: "resurrected-candidate" | "confirmation-shaken" | "holds" | "nothing-to-examine";
  examinedAt: string;
};

/** Operator-accepted deep-investigation refinement (PR-6b). Set on an RcaReport
 *  when the operator applied a confirmed autonomous orchestrator run's conclusion
 *  back into the report. The original root cause is preserved so the report can
 *  show a reversible "was: …" audit line — the write-back is never silent. */
export type OrchestratorRefinement = {
  /** The orchestrator run's outcome at accept time (always "confirmed" — the
   *  Apply action is only offered for confirmed runs). */
  outcome: string;
  /** The confirmed run's causal chain, persisted for cold-load rendering. */
  causalChain: CausalChainLink[];
  /** ISO timestamp the operator applied the refinement. */
  refinedAt: string;
  /** The report's root cause before this refinement overwrote it. */
  originalRootCause: string;
  /** The operator's free-text steer at the pause, if any (PR-4 lead). */
  operatorNotes?: string;
  /** The persisted `orchestrator:complete` event id this refinement was applied
   *  from. Lets a re-apply tell "same run, idempotent retry" (preserve the true
   *  original) from "a NEW deep run" (the current report value becomes the
   *  before), so the audit trail stays correct across multiple deep runs. */
  appliedCompleteEventId?: string;
  /** True when the report's narrative (summary/trigger/impact/timeline/factors/
   *  actions) was regenerated by an LLM pass to fit the confirmed cause. False/
   *  unset means only rootCause + confidence were merged (the LLM refine was
   *  skipped or failed and we fell back to the field-merge). */
  resynthesized?: boolean;
};

export type RcaReport = {
  service: string;
  severity: "low" | "medium" | "high" | "critical";
  summary: string;
  impact: {
    duration: string;
    description: string;
  };
  trigger: string;
  rootCause: string;
  contributingFactors: string[];
  timeline: TimelineEvent[];
  evidence: {
    metrics: string[];
    logs: string[];
    infra: string[];
    changes?: string[];
  };
  dashboardLinks: string[];
  recommendedActions: string[];
  confidence: "low" | "medium" | "high";
  confidenceScore: number;
  investigatedAt: string;
  skillsUsed?: string[];
  timeRange?: { from: string; to: string };
  /** Tool calls captured per evidence phase (keyed by phase: metrics/logs/infra/changes).
   *  Carried through from the workflow so the UI can build observation-level
   *  Grafana deep links. */
  evidenceToolCalls?: Record<string, EvidenceToolCall[]>;
  /** Hypothesis-loop output (Step 2). Unset on the default single-pass path. */
  hypotheses?: RankedHypothesis[];
  ruledOut?: RuledOutHypothesis[];
  loopOutcome?: "confirmed" | "undetermined" | "exhausted";
  /** Deep-mode re-examination (Step 3). Set only when deep mode was triggered. */
  deepMode?: DeepModeReport;
  /** Operator-accepted autonomous-orchestrator refinement (PR-6b). Set only when
   *  the operator applied a confirmed deep run's conclusion back into this report. */
  orchestratorRefined?: OrchestratorRefinement;
};

export type InvestigationIntent =
  | { intent: "investigation"; service?: string }
  | { intent: "question" };
